### ISSUE TITLE
install errror

### ISSUE THREAD

**Issue by hangyan** [kefranabg/readme-md-generator#59]
>  npx readme-md-generator

output is:
npx: installed 114 in 41.99s
Unexpected token (

**Comment by sahil97** [comment]
Could you please elaborate on the error or give more of a stack trace regarding the issue.
Also, please specify your environment ( OS, npm version ) so I can try to recreate the error.
P.S. Just tried it, worked as expected.

**Comment by kefranabg** [comment]
Hi @sahil97, could you also provide your node version ?

**Comment by sahil97** [comment]
Yup. Sorry I forgot to write my own version.
Node 10.15.3 on Ubuntu 16.04.6 LTS.

**Comment by kefranabg** [comment]
I'm not able to reproduce ... I released a new version, could you test it again ?

**Comment by hangyan** [comment]
still not working...

OS: 10.14.2

![image](https://user-images.githubusercontent.com/3939015/59959419-58d29f80-94e9-11e9-99fc-7294e33affbc.png)

**Comment by hangyan** [comment]
![image](https://user-images.githubusercontent.com/3939015/59959423-70aa2380-94e9-11e9-9b75-3d7706cdf19e.png)

**Comment by hangyan** [comment]
![image](https://user-images.githubusercontent.com/3939015/59959436-caaae900-94e9-11e9-9934-9a73c5d2b12f.png)

after install the latest npm. still not working...

**Comment by kefranabg** [comment]
@hangyan you have node 6.4 installed, just install a recent version of node and it will work

**Comment by hangyan** [comment]
@kefranabg yes, it works . thanks very much. May be it's better to add a note on the doc about this error?
